// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "/*\r\n * renexmoe v1.1.6 (https://github.com/186526/onemanager-theme-renexmoe)\r\n * Copyright 2020-2021 186526 <i@186526.xyz>\r\n * Licensed under GPL-3.0\r\n */\r\n@font-face {\r\n  font-family: \"Product Sans\";\r\n  src: local(\"Product Sans Regular\"), local(\"Google Sans Regular\"),\r\n    url(https://cdn.jsdelivr.net/gh/186526/jsdelivr@1.1.8/static/ProductSans-Regular.woff2)\r\n      format(\"woff2\");\r\n}\r\n\r\nbody {\r\n  font-family: Roboto, Noto Sans SC, Noto, Helvetica, Arial, sans-serif;\r\n}\r\n\r\n.mdui-container {\r\n  max-width: 950px;\r\n}\r\n\r\n.mdui-drawer-close {\r\n  display: none;\r\n}\r\n\r\n.mdui-drawer .mdui-list-item {\r\n  padding-left: 20px;\r\n  border-radius: 0 50px 50px 0;\r\n}\r\n\r\n.mdui-toolbar > a,\r\n.mdui-chip-title,\r\n.mdui-dialog-title {\r\n  font-family: Product Sans, Noto Sans SC, Roboto, Noto, Helvetica, Arial,\r\n    sans-serif;\r\n}\r\n\r\nfooter a {\r\n  text-decoration: none;\r\n}\r\n\r\n.mdui-chip {\r\n  margin: 20px;\r\n}\r\n\r\n.mdui-typo h1,\r\n.mdui-typo h2,\r\n.mdui-typo h3,\r\n.mdui-typo h4,\r\n.mdui-typo h5,\r\n.mdui-typo h6 {\r\n  font-family: Product Sans, Noto Sans SC;\r\n  margin-top: 0.2em;\r\n}\r\n\r\n@media (max-width: 740px) {\r\n  .mdui-col-sm-2,\r\n  .mdui-col-sm-3,\r\n  .forcedownload {\r\n    display: none;\r\n  }\r\n\r\n  .mdui-col-xs-12 {\r\n    width: 100%;\r\n  }\r\n}\r\n\r\n@media (max-width: 1024px) {\r\n  .mdui-drawer .mdui-list-item {\r\n    margin-right: 5px;\r\n  }\r\n}\r\n\r\n.mdui-list-item-icon {\r\n  --iconcolor: #656565;\r\n  color: var(--iconcolor) !important;\r\n}\r\n\r\n.mdui-theme-layout-dark .mdui-list-item-icon {\r\n  --iconcolor: #dadada !important;\r\n}\r\n\r\n.mdui-theme-layout-dark .mdui-list-item-active{\r\n  --color-active: rgb(255, 255, 255) !important;\r\n}\r\n\r\n.mdui-typo {\r\n  border-radius: 8px;\r\n}\r\n\r\n.mdui-dialog {\r\n  border-radius: 8px;\r\n}\r\n\r\n/* .mdui-container .mdui-list-item {\r\n  border-radius: 50px;\r\n} */\r\n\r\n#file {\r\n  margin-top: 1%;\r\n}\r\n\r\n#head-md,\r\n#readme-md {\r\n  display: none;\r\n}\r\n\r\n.mdui-theme-layout-dark .hljs-keyword,\r\n.hljs-selector-tag {\r\n  color: #dadada !important;\r\n}\r\n\r\nhtml *::-webkit-scrollbar {\r\n  width: 6px;\r\n  height: 4px;\r\n  border-radius: 4px;\r\n}\r\nhtml ::-webkit-scrollbar-thumb {\r\n  background: rgba(0, 0, 0, 0.3);\r\n}\r\n\r\n.mdui-dialog-actions .mdui-btn {\r\n  border-radius: 4px;\r\n}\r\n\r\n.mdui-menu {\r\n  border-radius: 6px;\r\n}\r\n";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}